### ISSUE TITLE
Ruby dependencies require manual synchronization wth arizona-bootstrap.

### ISSUE THREAD

**Issue by mmunro-ltrr** [az-digital/az-node-jre-jekyll#5]
## Problem/Motivation
Developers working on arizona-bootstrap need to make az-node-jre-jekyll pull requests as well.

### Describe the bug
The Ruby development environment within the az-node-jre-jekyll Docker image is synchronized with neither the upstream twbs/bootstrap v4-dev configuration, nor the dependent arizona-bootstrap configuration.

### To Reproduce

Compare:

1. https://github.com/twbs/bootstrap/blob/v4-dev/Gemfile.lock
2. https://github.com/az-digital/az-node-jre-jekyll/blob/master/Gemfile.lock
3. https://github.com/az-digital/arizona-bootstrap/blob/master/Gemfile.lock

The versions only match adequately on a good day, after manual synchronization.

## Proposed resolution
No change in this repository might suffice for arizona-bootstrap: the drastic resolution of no longer using the Docker image defined here might be best in that case.

**Comment by danahertzberg** [comment]
Not necessary if https://app.zenhub.com/workspaces/quickstart-20-5e8f25351c5b8596956ebb92/issues/az-digital/arizona-bootstrap/219 gets completed

**Comment by danahertzberg** [comment]
Martin says this is ancient history :)
